function pi --wraps pi --description "pi.dev coding agent: auto-install via npm + pin tmux window name"
    if not command -q pi
        if not command -q npm
            printf '  pi: npm not found; install Node.js first\n' >&2
            return 127
        end
        printf '  Installing pi...\n'
        npm install -g @earendil-works/pi-coding-agent
    end

    command -q dots-skills; and dots-skills ensure pi

    # The theme named in pi's settings is generated by the theme.d adapter, so
    # a machine that has not switched themes since install has no theme file
    # and pi falls back to its built-in dark without saying so. Re-apply the
    # current theme once to render it.
    set -l pi_agent_dir (set -q PI_CODING_AGENT_DIR && echo $PI_CODING_AGENT_DIR || echo $HOME/.pi/agent)
    if command -q theme; and not test -f $pi_agent_dir/themes/dots.json
        theme (theme --current) >/dev/null
    end

    _ai_run_pinned pi pi $argv
end
