format = """
$directory\
$character"""

right_format = """
$cmd_duration\
$git_branch\
$git_status\
$java\
$python\
$nodejs\
$docker_context\
$kubernetes"""

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'

[directory]
truncation_length = 1
truncate_to_repo = true
style = 'bold cyan'

[git_branch]
format = '[$symbol$branch]($style) '
symbol = ' '
style = 'bold purple'

[git_status]
format = '($stashed$staged$modified$untracked$conflicted$ahead_behind)'
stashed = '[*${count}](yellow) '
staged = '[+${count}](green) '
modified = '[!${count}](red) '
untracked = '[?${count}](blue) '
conflicted = '[=${count}](bold red) '
ahead = '[⇡${count}](green) '
behind = '[⇣${count}](red) '
diverged = '[⇕⇡${ahead_count}⇣${behind_count}](bold red) '

[java]
format = '[$symbol($version)]($style) '
symbol = ' '

[python]
format = '[$symbol($version)($virtualenv)]($style) '
symbol = ' '

[nodejs]
format = '[$symbol($version)]($style) '
symbol = ' '

[docker_context]
format = '[$symbol$context]($style) '
symbol = ' '

[kubernetes]
disabled = true
format = '[$symbol$context(/$namespace)]($style) '
symbol = '☸ '

[cmd_duration]
min_time = 0
show_milliseconds = true
format = "[$duration](bold yellow) "
