set -l commands pull create create-linux bootstrap start stop ssh sync status ip doctor destroy clean help

complete -c vm -f
complete -c vm -s f -l flavor -x -a 'archlinux macos' -d 'VM flavor'
complete -c vm -n "not __fish_seen_subcommand_from $commands" -a pull -d 'Pull latest base image'
complete -c vm -n "not __fish_seen_subcommand_from $commands" -a create -d 'Create VM from base image'
complete -c vm -n "not __fish_seen_subcommand_from $commands" -a create-linux -d 'Create blank Linux VM from ISO'
complete -c vm -n "not __fish_seen_subcommand_from $commands" -a bootstrap -d 'Install tart-guest-agent (macOS)'
complete -c vm -n "not __fish_seen_subcommand_from $commands" -a start -d 'Start the VM'
complete -c vm -n "not __fish_seen_subcommand_from $commands" -a stop -d 'Stop the VM'
complete -c vm -n "not __fish_seen_subcommand_from $commands" -a ssh -d 'SSH in (forwards agent + API keys)'
complete -c vm -n "not __fish_seen_subcommand_from $commands" -a sync -d 'Rsync dotfiles + re-install'
complete -c vm -n "not __fish_seen_subcommand_from $commands" -a status -d 'Show VM state'
complete -c vm -n "not __fish_seen_subcommand_from $commands" -a ip -d 'Show VM IP address'
complete -c vm -n "not __fish_seen_subcommand_from $commands" -a doctor -d 'Check host dependencies and VM state'
complete -c vm -n "not __fish_seen_subcommand_from $commands" -a destroy -d 'Delete the VM'
complete -c vm -n "not __fish_seen_subcommand_from $commands" -a clean -d 'Delete all local VMs'
complete -c vm -n "not __fish_seen_subcommand_from $commands" -a help -d 'Show help'
complete -c vm -n '__fish_seen_subcommand_from create create-linux' -l force -d 'Destroy existing VM first'
complete -c vm -n '__fish_seen_subcommand_from start' -l graphics -d 'Boot with graphical display'
complete -c vm -n '__fish_seen_subcommand_from start' -l vnc -d 'Boot with VNC server'
complete -c vm -n '__fish_seen_subcommand_from start' -l headless -d 'Boot headless (no display)'
