# ── Plugins (TPM) ───────────────────────────────────
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.local/share/tmux/plugins"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'sainnhe/tmux-fzf'

set -g @thumbs-key t
set -g @thumbs-command 'echo -n {} | pbcopy'

set -g @fzf-url-bind u
set -g @fzf-url-fzf-options '-w 60% -h 40% --prompt="  " --border-label=" Open URL "'
set -g @fzf-url-history-limit '2000'

TMUX_FZF_LAUNCH_KEY="C-f"

if "test ! -d $HOME/.local/share/tmux/plugins/tpm" \
   "run-shell -b 'git clone https://github.com/tmux-plugins/tpm $HOME/.local/share/tmux/plugins/tpm && $HOME/.local/share/tmux/plugins/tpm/bin/install_plugins'"

if "test -x $HOME/.local/share/tmux/plugins/tpm/tpm" \
   "run '$HOME/.local/share/tmux/plugins/tpm/tpm'"
