complete -c vm -f
complete -c vm -s f -l flavor -x -a 'archlinux macos' -d 'VM flavor'
complete -c vm -n __fish_use_subcommand -a pull -d 'Pull latest base image'
complete -c vm -n __fish_use_subcommand -a create -d 'Create VM from base image'
complete -c vm -n __fish_use_subcommand -a create-linux -d 'Create blank Linux VM from ISO'
complete -c vm -n __fish_use_subcommand -a bootstrap -d 'Install tart-guest-agent (macOS)'
complete -c vm -n __fish_use_subcommand -a start -d 'Start the VM'
complete -c vm -n __fish_use_subcommand -a stop -d 'Stop the VM'
complete -c vm -n __fish_use_subcommand -a ssh -d 'SSH in (forwards agent + API keys)'
complete -c vm -n __fish_use_subcommand -a sync -d 'Rsync dotfiles + re-install'
complete -c vm -n __fish_use_subcommand -a status -d 'Show VM state'
complete -c vm -n __fish_use_subcommand -a ip -d 'Show VM IP address'
complete -c vm -n __fish_use_subcommand -a destroy -d 'Delete the VM'
complete -c vm -n __fish_use_subcommand -a clean -d 'Delete all local VMs'
complete -c vm -n __fish_use_subcommand -a help -d 'Show help'
complete -c vm -n '__fish_seen_subcommand_from create create-linux' -l force -d 'Destroy existing VM first'
complete -c vm -n '__fish_seen_subcommand_from start' -l graphics -d 'Boot with graphical display'
complete -c vm -n '__fish_seen_subcommand_from start' -l vnc -d 'Boot with VNC server'
complete -c vm -n '__fish_seen_subcommand_from start' -l headless -d 'Boot headless (no display)'
