# ── Theme environment ────────────────────────────────────
# Source generated theme env vars (BAT_THEME, etc.)
# Generated by: theme <name>
[[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/theme/env.zsh" ]] && \
  source "${XDG_CONFIG_HOME:-$HOME/.config}/theme/env.zsh"
