# ── Theme environment ────────────────────────────────────
# Source unified theme env file (THEME_NAME, THEME_VARIANT, BAT_THEME, etc.)
# Generated by: theme <name>
[[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/theme/env" ]] && \
  source "${XDG_CONFIG_HOME:-$HOME/.config}/theme/env"
