# ── Theme environment ────────────────────────────────────
# Parse theme data file and export what the shell needs.
# Generated by: theme <name>
local _tf="${XDG_CONFIG_HOME:-$HOME/.config}/theme/current"
if [[ -f "$_tf" ]]; then
  while IFS='=' read -r _tk _tv; do
    case "$_tk" in
      bat_theme) export BAT_THEME="$_tv" ;;
    esac
  done < "$_tf"
fi
