default_channel = "files"

[keybindings]
ctrl-d = "scroll_preview_half_page_down"
ctrl-u = "scroll_preview_half_page_up"
ctrl-f = "scroll_preview_half_page_down"
ctrl-b = "scroll_preview_half_page_up"

[ui]
theme = "catppuccin"

[ui.input_bar]
border_type = "rounded"

[ui.results_panel]
border_type = "rounded"

[ui.preview_panel]
border_type = "rounded"
